project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .

preserve_hierarchy: true


files:
  # Resonance.Core Shared Resources (.resx)
  - source: /src/Resonance.Core/Resources/Strings.resx
    translation: /src/Resonance.Core/Resources/Strings.%locale%.resx

  # Resonance.WinUI C# Resources (.resx)
  - source: /src/Resonance.WinUI/Resources/Strings.resx
    translation: /src/Resonance.WinUI/Resources/Strings.%locale%.resx
