<Project>
    <PropertyGroup>
        <!--
          This file defines shared MSBuild properties for all projects in the solution.
          NuGet package versions are managed centrally in Directory.Packages.props.
        -->

        <!-- General Project Properties -->
        <LangVersion>preview</LangVersion>

        <!-- Target Framework Versions -->
        <NetVersion>10.0</NetVersion>
        <WindowsSdkVersion>10.0.26100</WindowsSdkVersion>
        <WindowsTargetPlatformMinVersion>10.0.17763.0</WindowsTargetPlatformMinVersion>
        <WindowsTargetPlatformMaxTestedVersion>10.0.26100.0</WindowsTargetPlatformMaxTestedVersion>
        <AppxPackageVersion>2.3.0.0</AppxPackageVersion>
    </PropertyGroup>
</Project>
