// <auto-generated>
// This file was created by the Nagi toolset.
// </auto-generated>

namespace Nagi.WinUI.Models;

/// <summary>
///     Defines the available background materials for the music player.
/// </summary>
public enum PlayerBackgroundMaterial
{
    /// <summary>
    ///     Uses the default Acrylic material (glass-like blur).
    /// </summary>
    Acrylic,

    /// <summary>
    ///     Uses a solid, opaque background color.
    /// </summary>
    Solid
}
